---
knit: "bookdown::render_book"
title: "Structural Equation Modeling for Ecology and Evolution"
author: ["Jarrett Byrnes", "Jon Lefcheck", "James Grace"]
url: 'http\://jebyrnes.github.io/sem'
github-repo: jebyrnes/sem
twitter-handle: jebyrnes
site: bookdown::bookdown_site
documentclass: book
---

# Agenda {-}

0) Setup bookdown x
	- Create roadmap for this meeting x
	- Create a roadmap for an SEM learner 

1. Formalizing how exogenous variables are included in the basis set

2. Can you statistically compare two C statistics? Yes.  

3. GLMs and C-statistics
	- low hanging urgent fruit  

4. Nonlinearities and the C-statistics
	- Polynomial terms  
	- Interaction effects    

5. Testing indirect effects  
	- p-values based tests, etc.  

6. Latent Variables in a Piecewise Framework  

7. Fitting and evaluating True multilevel models  
    - In a nutshell, you need to capture those intercepts into a different model in a separate dataset
    - Algorithmic solution?

8. Standardized coefficients for nonlinear variables & glms  

9. Prediction with error (maybe with Jon this afternoon?)  
	- i.e. for forecasting  

10. Formalization of correlated errors 
	- Derived v. estimated parameter?  

11. Human-understandable explanation of the front-door and back-door criteria for better model creation  
  - maybe revisit at end of 1st day of a class  
  
12. Categorical variables in a piecewise approach
	- General guidelines  
	- Comparison to multigroup modeling?  

13. Model evaluation in a Bayesian context

14. Roadmap for piecewiseSEM
