# (APPENDIX) Appendices  {-}

# Agenda and Notes from February Meeting  

0. Setup bookdown x
- Create roadmap for this meeting x
- Create a roadmap for an SEM learner 

1. Formalizing how exogenous variables are included in the basis set x
- Maybe provide an additional output of correlation between exogenous variables  
- But - no reason to include those in calculating Fisher's C

2. Can you statistically compare two C statistics? Yes.  x

3. GLMs and C-statistics x
- low hanging urgent fruit  

4. Nonlinearities and the C-statistics x
- Polynomial terms  
- Interaction effects  
- Jim says ignore them, then says don't  
- ignore, but diagnostics are separate from independence tests  


5. Testing indirect effects  x
- p-values based tests, etc.  
- Nah - don't do p-value based testing
- Can use Jarrett's predict function to get total effect
- Can then subtract direct effect if it is there
- Other tests of indirect pathways need to be done by hand

6. Latent Variables in a Piecewise Framework  x
- Can you use factor scores as another variable in the model

7. Fitting and evaluating True multilevel models  
- In a nutshell, you need to capture those intercepts into a different model in a separate dataset
- Algorithmic solution?

8. Standardized coefficients for nonlinear variables & glms  ??   
- HAHAHAHAHA - man have we failed here so far

9. Prediction with error (maybe with Jon this afternoon?) x  
- i.e. for forecasting  
- Simulation is the answer  
- The problem is random effects structure  
- Perhaps only use fixed effects?  
- And/or sort out random effect usage  
- The biggest problem you will have is nonlinear models

10. Formalization of correlated errors x
- Derived v. estimated parameter?  
- Derived! piecewise estimation handles this  

11. Human-understandable explanation of the front-door and back-door criteria for better model creation x  
- maybe revisit at end of 1st day of a class  
- Think about temporal aspect of causality  
- see picture

12. Categorical variables in a piecewise approach x
- General guidelines  
- Comparison to multigroup modeling?  
- Fit two different SEMs and evaluate if parameters are different
- Constraints not needed?
- Make a table comparing parameters across groups
- Endogenous:  Binomial is a categorical response
- Multiple categorical levels - multinomial logistic regression  
- `multinom` function in `nnet` package
- http://stats.idre.ucla.edu/r/dae/multinomial-logistic-regression/  
  - Standardization is......trickier  

13. Model evaluation in a Bayesian context  ??
- No one so far believe DIC
- Posterior Predictive P-Value
- How do you evaluate a basis set?
- How do you calculate WAIC?
- Classic Bayesian SEM works with Covariance matrices - so, a single likelihood
- Statisticians don't love piecemeal nature of Dsep
- Sum Bayesian p-values?
- Jim says 'good luck with that' - lots of issues, limit to what he can focus on
- Need to talk with a Bayesian statistician

14. Roadmap for piecewiseSEM  

15. Teaching roadmap  
- http://www.nwrc.usgs.gov/SEM/ (old)
- http://structuralequations.org (old)  
- http://bit.ly/graceSEM
